# Generated by Django 5.0 on 2024-01-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeitem',
            old_name='ingredient',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='recipeitem',
            old_name='recipe_item',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='measure',
            field=models.CharField(choices=[('gram', 'грам'), ('centimeter', 'сантиметр'), ('piece', 'штук')], max_length=20),
        ),
    ]
