# Generated by Django 5.0 on 2024-01-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('measure', models.CharField(choices=[('kilogram', 'кілограм'), ('meter', 'метри'), ('piece', 'штук')], max_length=50)),
                ('category', models.CharField(choices=[('ingredient', 'Інгредієнт'), ('additional_product', 'Додаткові продукти'), ('package', 'Пакети'), ('label', 'Етикетки'), ('crouton', 'Сухарики'), ('box', 'Ящики')], max_length=50)),
            ],
        ),
    ]
