# Generated by Django 5.0 on 2024-01-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ingredient', 'Інгредієнт'), ('additional_product', 'Додаткові продукти'), ('package', 'Пакети'), ('label', 'Етикетки'), ('crouton', 'Сухарики'), ('box', 'Ящики')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='measure',
            field=models.CharField(choices=[('kilogram', 'кілограм'), ('meter', 'метри'), ('piece', 'штук')], max_length=20),
        ),
    ]
