# Generated by Django 5.0 on 2024-01-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseitem',
            old_name='warehouse_record_item',
            new_name='warehouse_item',
        ),
    ]
