# Generated by Django 5.0 on 2024-01-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
